name: Filter MobiSDEC CSV

on:
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  filter-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run filter script
        run: python filter_mobisdec.py

      - name: Upload filtered CSV as artifact
        uses: actions/upload-artifact@v3
        with:
          name: mobisdec-filtré
          path: mobisdec_filtré.csv
