name: Filter MobiSDEC CSV

on:
  schedule:
    - cron: '0 4 * * *'  # workflow_dispatch:  # Permet de lancer manuellement depuis l'interface GitHub

jobs:
  filter-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run filter script
        run: python script.py

      - name: Upload filtered CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobisdec-filtré
          path: mobisdec_filtré.csv

      - name: Send CSV to Zapier
        run: |
          curl -X POST -F "file=@mobisdec_filtré.csv" https://hooks.zapier.com/hooks/catch/25244139/ushmo05/
