name: Filter MobiSDEC CSV

on:
  schedule: #workflow_dispatch: #
    - cron: '0 4 * * *'


jobs:
  filter-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run filter script
        run: python script.py

      - name: Upload filtered CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobisdec-filtré
          path: mobisdec_filtré.csv

      - name: Send CSV to Zapier
        run: |
          curl -X POST -F "file=@mobisdec_filtré.csv" https://a7adbb51d943e1b0b4ff2f51b09d36.f9.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/76208c4c965c4b5db53554d3ca2e6381/triggers/manual/paths/invoke?api-version=1
          
